name: "Beszel-Agent"
description: "Beszel-Agent for Home Assistant"
url: "https://github.com/matthewhadley/homeassistant-beszel-agent"
version: "0.18.2"
slug: "beszel-agent"
init: false
stdin: true
hassio_api: false
homeassistant_api: false
docker_api: true
host_network: true
options:
  public_key: null
schema:
  public_key: str
  hub_url: str?
  port: str?
  token: str?
arch:
  - aarch64
  - amd64
image: "matthewhadley/homeassistant-beszel-agent-{arch}"
